packages:
  - chrome-extension
  - pages/*
  - packages/*
  - tests/*

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@swc/core"
  - edgedriver
  - esbuild
  - geckodriver
  - unrs-resolver

minimumReleaseAge: 20160
minimumReleaseAgeExclude:
  - react@19.2.1
  - react-dom@19.2.1

overrides:
  esbuild@<=0.24.2: ">=0.25.0"
  react@<=19.2.0: ">=19.2.1"
