export { changeTabGroupColor } from './lib/actions/tabGroups/changeTabGroupColor.js'
export { collapseTabGroup } from './lib/actions/tabGroups/collapseTabGroup.js'
export { copyTabGroupUrls } from './lib/actions/tabGroups/copyTabGroupUrls.js'
export { expandTabGroup } from './lib/actions/tabGroups/expandTabGroup.js'
export { moveTabGroupBackward } from './lib/actions/tabGroups/moveTabGroupBackward.js'
export { moveTabGroupForward } from './lib/actions/tabGroups/moveTabGroupForward.js'
export { moveTabGroupToNewWindow } from './lib/actions/tabGroups/moveTabGroupToNewWindow.js'
export { renameTabGroup } from './lib/actions/tabGroups/renameTabGroup.js'
export { toggleTabGroupCollapsed } from './lib/actions/tabGroups/toggleTabGroupCollapsed.js'
export { activateTab } from './lib/actions/tabs/activateTab.js'
export { addTabToGroup } from './lib/actions/tabs/addTabToGroup.js'
export { addTabToNewGroup } from './lib/actions/tabs/addTabToNewGroup.js'
export { closeOtherTabs } from './lib/actions/tabs/closeOtherTabs.js'
export { closeTab } from './lib/actions/tabs/closeTab.js'
export { closeTabs } from './lib/actions/tabs/closeTabs.js'
export { closeTabsAfter } from './lib/actions/tabs/closeTabsAfter.js'
export { copyTabTitle } from './lib/actions/tabs/copyTabTitle.js'
export { copyTabTitleAndUrl } from './lib/actions/tabs/copyTabTitleAndUrl.js'
export { copyTabUrl } from './lib/actions/tabs/copyTabUrl.js'
export { duplicateTab } from './lib/actions/tabs/duplicateTab.js'
export { moveTabBackward } from './lib/actions/tabs/moveTabBackward.js'
export { moveTabForward } from './lib/actions/tabs/moveTabForward.js'
export { moveTabToNewWindow } from './lib/actions/tabs/moveTabToNewWindow.js'
export { moveTabToWindow } from './lib/actions/tabs/moveTabToWindow.js'
export { muteTab } from './lib/actions/tabs/muteTab.js'
export { pinTab } from './lib/actions/tabs/pinTab.js'
export { reloadTab } from './lib/actions/tabs/reloadTab.js'
export { removeTabFromGroup } from './lib/actions/tabs/removeTabFromGroup.js'
export { ungroupTabs } from './lib/actions/tabs/ungroupTabs.js'
export { unmuteTab } from './lib/actions/tabs/unmuteTab.js'
export { unpinTab } from './lib/actions/tabs/unpinTab.js'
export { closeWindow } from './lib/actions/windows/closeWindow.js'
export { copyAllUrlsInWindow } from './lib/actions/windows/copyAllUrlsInWindow.js'
export { focusWindow } from './lib/actions/windows/focusWindow.js'
export { muteAllTabsInWindow } from './lib/actions/windows/muteAllTabsInWindow.js'
export { reloadAllTabsInWindow } from './lib/actions/windows/reloadAllTabsInWindow.js'
export { unmuteAllTabsInWindow } from './lib/actions/windows/unmuteAllTabsInWindow.js'
export {
  BrowserStoreProvider,
  type BrowserStoreProviderProps,
} from './lib/BrowserStoreProvider.js'
export type { BrowserTab } from './lib/tab/BrowserTab.js'
export type { BrowserTabID } from './lib/tab/BrowserTabID.js'
export { createBrowserTab } from './lib/tab/createBrowserTab.js'
export { refreshBrowserTab } from './lib/tab/refreshBrowserTab.js'
export { removeBrowserTabById } from './lib/tab/removeBrowserTabById.js'
export { updateBrowserTabById } from './lib/tab/updateBrowserTabById.js'
export { useBrowserTabById } from './lib/tab/useBrowserTabById.js'
export { useBrowserTabs } from './lib/tab/useBrowserTabs.js'
export { useBrowserTabsById } from './lib/tab/useBrowserTabsById.js'
export { useBrowserTabsByWindowId } from './lib/tab/useBrowserTabsByWindowId.js'
export type { BrowserTabGroup } from './lib/tabGroup/BrowserTabGroup.js'
export type { BrowserTabGroupColor } from './lib/tabGroup/BrowserTabGroup.js'
export type { BrowserTabGroupID } from './lib/tabGroup/BrowserTabGroupID.js'
export { useBrowserTabGroupById } from './lib/tabGroup/useBrowserTabGroupById.js'
export { useBrowserTabGroups } from './lib/tabGroup/useBrowserTabGroups.js'
export { useBrowserTabGroupsByWindowId } from './lib/tabGroup/useBrowserTabGroupsByWindowId.js'
export { usePlatformInfo } from './lib/usePlatformInfo.js'
export { type TabListItem, useTabListItems } from './lib/useTabListItems.js'
export type { BrowserWindow } from './lib/window/BrowserWindow.js'
export type { BrowserWindowID } from './lib/window/BrowserWindowID.js'
export { createBrowserWindow } from './lib/window/createBrowserWindow.js'
export { removeBrowserWindowById } from './lib/window/removeBrowserWindowById.js'
export { updateBrowserWindowById } from './lib/window/updateBrowserWindowById.js'
export { useBrowserWindowById } from './lib/window/useBrowserWindowById.js'
export { useBrowserWindows } from './lib/window/useBrowserWindows.js'
export { useBrowserWindowsById } from './lib/window/useBrowserWindowsById.js'
export { useCurrentBrowserWindow } from './lib/window/useCurrentBrowserWindow.js'
export { useFocusedBrowserWindow } from './lib/window/useFocusedBrowserWindow.js'
export { useSelectedWindowId } from './lib/window/useSelectedWindowId.js'
export { useSetSelectedWindowId } from './lib/window/useSetSelectedWindowId.js'
